server:
  port: 7001
  servlet:
    context-path: /product
spring:
  application:
    name: product
eureka:
  client:
    service-url:
      defaultZone:  http://eureka-server1:8888/eureka/eureka,http://eureka-server1:8889/eureka/eureka
  instance:
    hostname: product02
    prefer-ip-address: true

